### ISSUE TITLE
Adds the Fee Twice

### ISSUE THREAD

**Issue by webusat** [magecomp/magento2-extra-fee#3]
Hi,

This seems to add the fee twice.  Any ideas?

**Comment by archanab20** [comment]
Yes, I have the same issue but I found solution,

Update grandTotal in below files

Model/Total/Fee.php

Model/Quote/Total/Fee.php

 Change 
 $total->setGrandTotal($total->getGrandTotal() + $fee);
 $total->setBaseGrandTotal($total->getBaseGrandTotal() + $fee);

TO
 $total->setGrandTotal($total->getGrandTotal());
 $total->setBaseGrandTotal($total->getBaseGrandTotal());

because it's already update in this file,

Plugin/Checkout/Model/ShippingInformationManagement.php

Clean cache and check, hope it helps you.

**Comment by nitaipanda** [comment]
![image](https://user-images.githubusercontent.com/20333565/62602309-163a1a80-b911-11e9-9e04-bb3f475a9440.png)
 see this issue

**Comment by nitaipanda** [comment]
Plugin/Checkout/Model/ShippingInformationManagement.php not get fee value

**Comment by nitaipanda** [comment]
please solve this issues as soon as possible

**Comment by magecomp** [comment]
Checkout our latest version updated,
